In [39]:
import numpy as np
import pandas as pd
import os
import glob

In [40]:
train_files = [file for file in glob.glob("../output/*train*.csv")]
train_files

['../output/tfidf_lgb_train_5fold.csv',
 '../output/des_word_svd_200_char_svd_1000_title_200_resnet50_500_lgb_5fold_train.csv',
 '../output/des_word_svd_200_char_svd_1000_title_200_resnet50_500_incepv3_logprice_lgb_5fold_train.csv',
 '../output/des_word_50000_nwords_title_50000_lower_swr_resnet50_500_logprice_params_ridge_5fold_train.csv',
 '../output/des_word_10000_nwords_title_5000_lower_swr_resnet50_500_logprice_params_lgb_5fold_train.csv',
 '../output/pk_nn_starter_2347_res50_mlp_5fold_train.csv',
 '../output/pk_ridge_2360_res50_5fold_train.csv',
 '../output/pk_nn_starter_2347_res50_mlp_10fold_train.csv',
 '../output/pk_2282_catboost_train.csv',
 '../output/des_word_10000_nwords_title_5000_params_5000_lower_swr_resnet50_500_logprice_params_incep30_lgb_5fold_train.csv',
 '../output/pk_ridge_2360_5fold_train.csv',
 '../output/des_word_10000_nwords_title_5000_lower_swr_resnet50_500_logprice_params_s1042_lgb_5fold_train.csv',
 '../output/mercari_no2_sol_emb_nn_5fold_train.csv',
 '../ou

In [62]:
train_files = [
 '../output/des_word_10000_nwords_title_5000_params_5000_lower_swr_resnet50_500_logprice_params_incep30_lgb_5fold_test.csv',
 '../output/des_word_50000_nwords_title_50000_lower_swr_resnet50_500_logprice_params_ridge_5fold_test.csv',
 '../output/des_word_10000_nwords_title_5000_lower_swr_resnet50_500_logprice_params_lgb_5fold_test.csv',    
 '../output/pk_ridge_2360_res50_5fold_train.csv',
 '../output/pk_2282_catboost_train.csv',
 '../output/mercari_no2_sol_emb_nn_5fold_train.csv',
 '../output/mercari_no2_sol_emb_nn_imtop1_5fold_train.csv',
 '../output/mercari_no2_sol_emb_50_price_nn_imtop1_5fold_train.csv',
 '../output/mercari_no2_sol_emb_50_price_mean_encode_nn_imtop1_5fold_train.csv',
 '../output/mercari_no2_sol_emb_50_price_mean_encode_seq_num_nn_imtop1_5fold_train.csv',
 '../output/mercari_no2_sol_emb_50_price_imtop1_itseq_nn_5fold_train.csv',
 '../output/mercari_no2_sol_emb_50_price_imtop1_deslen_itseq_nn_5fold_train.csv',
 '../output/mercari_no2_sol_emb_50_price_imtop1_city_itseq_nn_5fold_train.csv',
 '../output/mercari_no2_sol_emb_50_price_imtop1_city_param1_itseq_nn_5fold_train.csv',
 '../output/mercari_no2_sol_emb_50_price_nn_imtop1_db_params_3_5fold_train.csv',
 '../output/mercari_no2_sol_emb_50_price_deslen_nn_5fold_train.csv',
 '../output/mercari_no2_sol_emb_50_price_deslen_imquality_tilen_nn_5fold_train.csv',
 '../output/mercari_no2_sol_emb_50_price_deslen_imquality_nn_5fold_train.csv',
 '../output/mercari_no2_sol_emb_50_price_deslen_tilen_nn_5fold_train.csv',
 '../output/mercari_no2_sol_emb_50_price_deslen_tilen_ag_pr1_nn_5fold_train.csv',
 '../output/mercari_no2_sol_emb_50_price_deslen_ag_pr1_avgpool_nn_5fold_train.csv',
 '../output/mercari_no2_sol_emb_50_price_deslen_ag_pr1_nn_5fold_train.csv',
 '../output/mercari_no2_sol_emb_50_price_deslen_txfeatlen_nn_5fold_train.csv',
 '../output/mercari_no2_sol_emb_50_price_deslen_desvec10000_nn_5fold_train.csv',
]

In [63]:
import re

In [64]:
test_files = [re.sub('train', 'test', file) for file in train_files]
test_files

['../output/des_word_10000_nwords_title_5000_params_5000_lower_swr_resnet50_500_logprice_params_incep30_lgb_5fold_test.csv',
 '../output/des_word_50000_nwords_title_50000_lower_swr_resnet50_500_logprice_params_ridge_5fold_test.csv',
 '../output/des_word_10000_nwords_title_5000_lower_swr_resnet50_500_logprice_params_lgb_5fold_test.csv',
 '../output/pk_ridge_2360_res50_5fold_test.csv',
 '../output/pk_2282_catboost_test.csv',
 '../output/mercari_no2_sol_emb_nn_5fold_test.csv',
 '../output/mercari_no2_sol_emb_nn_imtop1_5fold_test.csv',
 '../output/mercari_no2_sol_emb_50_price_nn_imtop1_5fold_test.csv',
 '../output/mercari_no2_sol_emb_50_price_mean_encode_nn_imtop1_5fold_test.csv',
 '../output/mercari_no2_sol_emb_50_price_mean_encode_seq_num_nn_imtop1_5fold_test.csv',
 '../output/mercari_no2_sol_emb_50_price_imtop1_itseq_nn_5fold_test.csv',
 '../output/mercari_no2_sol_emb_50_price_imtop1_deslen_itseq_nn_5fold_test.csv',
 '../output/mercari_no2_sol_emb_50_price_imtop1_city_itseq_nn_5fold_tes

In [65]:
len(test_files)

24

In [66]:
select_index = [2,4, 6, 8, 9, 10, 11, 12, 13]

In [67]:
# train_files = [train_files[i] for i in select_index]
# test_files = [test_files[i] for i in select_index]

In [68]:
train_dfs = [pd.read_csv(f)for f in train_files]
test_dfs = [pd.read_csv(f)for f in test_files]

In [69]:
train_data = np.zeros([train_dfs[0].shape[0], len(train_dfs)])
for i, df in enumerate(train_dfs):
    train_data[:,i] = train_dfs[0].deal_probability.values
train_data.shape

(508438, 24)

In [70]:
test_data = np.zeros([test_dfs[0].shape[0], len(test_dfs)])
for i, df in enumerate(test_dfs):
    test_data[:,i] = test_dfs[0].deal_probability.values
test_data.shape

(508438, 24)

In [71]:
import pickle
with open('../input/layer_2_24m_train.p', 'wb') as f:
    pickle.dump(train_data, f)

In [72]:
import pickle
with open('../input/layer_2_24m_test.p', 'wb') as f:
    pickle.dump(test_data, f)

In [13]:
import lightgbm as lgb

In [89]:
model = lgb.Booster(model_file= '../weights/l2_8m_lgb_5fold_fold4.model')
model.feature_importance()

array([5054, 2408,  770,   84,    0,    0,    0,    0])

In [15]:
model = lgb.Booster(model_file= '../weights/l2_6m_lgb_5fold_fold0.model')
model.feature_importance()

array([6118, 2142,  630,    0,    0,    0])

In [14]:
model = lgb.Booster(model_file= '../weights/l2_9m_lgb_5fold_fold0.model')
model.feature_importance()

array([5964, 2170,  644,  112,    0,    0,    0,    0,    0])